# Generated by Django 3.1.4 on 2021-05-21 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacao',
            fields=[
                ('hab_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('fumador', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=40)),
                ('morada', models.CharField(max_length=100)),
                ('wc', models.IntegerField()),
                ('quartos', models.IntegerField()),
                ('area', models.IntegerField()),
                ('sol', models.CharField(max_length=1)),
                ('preco', models.FloatField()),
                ('faixa_etaria', models.CharField(max_length=10)),
                ('animais', models.BooleanField(default=False)),
                ('genero', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, default='images/alojamentos/default.png', upload_to='images/alojamentos/')),
                ('wifi', models.BooleanField(default=False)),
                ('limpeza', models.BooleanField(default=False)),
                ('ar_condicionado', models.BooleanField(default=False)),
                ('televisao', models.BooleanField(default=False)),
                ('fogao', models.BooleanField(default=False)),
                ('frigorifico', models.BooleanField(default=False)),
                ('metro', models.BooleanField(default=False)),
                ('autocarro', models.BooleanField(default=False)),
                ('extras', models.CharField(blank=True, default='Nenhum', max_length=200)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nascimento', models.DateField(null=True)),
                ('email', models.CharField(max_length=30)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, default='images/users/user.svg', upload_to='images/users/')),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('localidade', models.CharField(blank=True, max_length=50, null=True)),
                ('lingua', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Senhorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(null=True)),
                ('data_saida', models.DateField(null=True)),
                ('n_hospedes', models.IntegerField(default=1)),
                ('habitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.habitacao')),
                ('senhorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.senhorio')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('habitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.habitacao')),
                ('inquilino_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.inquilino')),
                ('senhorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.senhorio')),
            ],
        ),
        migrations.AddField(
            model_name='inquilino',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentItapp.utilizador'),
        ),
        migrations.CreateModel(
            name='HistoricoReservas',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('desde', models.DateField(null=True)),
                ('ate', models.DateField(null=True)),
                ('renda', models.IntegerField(null=True)),
                ('n_hospedes', models.IntegerField(default=1)),
                ('habitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitacao', to='rentItapp.habitacao')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquilinoHist', to='rentItapp.utilizador')),
                ('senhorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhorioHist', to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Habita',
            fields=[
                ('habitado_id', models.AutoField(primary_key=True, serialize=False)),
                ('desde', models.DateField()),
                ('ate', models.DateField()),
                ('renda', models.IntegerField()),
                ('valorAPagar', models.FloatField()),
                ('dia_pagamento', models.IntegerField()),
                ('n_hospedes', models.IntegerField(default=1)),
                ('habitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.habitacao')),
                ('inquilino_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='gere',
            fields=[
                ('gere_id', models.AutoField(primary_key=True, serialize=False)),
                ('hab_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.habitacao')),
                ('senhorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.senhorio')),
            ],
        ),
        migrations.CreateModel(
            name='Contacta',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquilino_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.inquilino')),
                ('senhorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.senhorio')),
            ],
        ),
        migrations.CreateModel(
            name='Avalia',
            fields=[
                ('avalia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=500)),
                ('senhorio', models.IntegerField()),
                ('limpeza', models.IntegerField()),
                ('vizinhanca', models.IntegerField()),
                ('inquilino', models.IntegerField()),
                ('habitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.habitacao')),
                ('inquilino_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Anunciosfav',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentItapp.habitacao')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentItapp.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentItapp.utilizador')),
            ],
        ),
    ]
